using FitnessTracker.Api.Data;

namespace FitnessTracker.Api;

// Built-in exercises for home training. MET: 3.5 light, 5.0 moderate, 8.0 vigorous (ACSM resistance training codes).
public static class LibrarySeed
{
    public static readonly (string Name, Equipment Equipment, MuscleGroup Muscle, double Met)[] Rows =
    [
        ("Dumbbell bench press", Equipment.Dumbbell, MuscleGroup.Chest, 5.0),
        ("Dumbbell floor press", Equipment.Dumbbell, MuscleGroup.Chest, 5.0),
        ("Dumbbell fly", Equipment.Dumbbell, MuscleGroup.Chest, 3.5),
        ("Dumbbell row", Equipment.Dumbbell, MuscleGroup.Back, 5.0),
        ("Renegade row", Equipment.Dumbbell, MuscleGroup.Back, 6.0),
        ("Dumbbell deadlift", Equipment.Dumbbell, MuscleGroup.Legs, 6.0),
        ("Romanian deadlift", Equipment.Dumbbell, MuscleGroup.Legs, 5.0),
        ("Goblet squat", Equipment.Dumbbell, MuscleGroup.Legs, 5.0),
        ("Dumbbell lunge", Equipment.Dumbbell, MuscleGroup.Legs, 5.0),
        ("Bulgarian split squat", Equipment.Dumbbell, MuscleGroup.Legs, 6.0),
        ("Dumbbell step-up", Equipment.Dumbbell, MuscleGroup.Legs, 5.0),
        ("Calf raise", Equipment.Dumbbell, MuscleGroup.Legs, 3.5),
        ("Dumbbell shoulder press", Equipment.Dumbbell, MuscleGroup.Shoulders, 5.0),
        ("Lateral raise", Equipment.Dumbbell, MuscleGroup.Shoulders, 3.5),
        ("Front raise", Equipment.Dumbbell, MuscleGroup.Shoulders, 3.5),
        ("Rear delt fly", Equipment.Dumbbell, MuscleGroup.Shoulders, 3.5),
        ("Arnold press", Equipment.Dumbbell, MuscleGroup.Shoulders, 5.0),
        ("Bicep curl", Equipment.Dumbbell, MuscleGroup.Arms, 3.5),
        ("Hammer curl", Equipment.Dumbbell, MuscleGroup.Arms, 3.5),
        ("Overhead tricep extension", Equipment.Dumbbell, MuscleGroup.Arms, 3.5),
        ("Tricep kickback", Equipment.Dumbbell, MuscleGroup.Arms, 3.5),
        ("Farmer carry", Equipment.Dumbbell, MuscleGroup.FullBody, 6.0),
        ("Dumbbell thruster", Equipment.Dumbbell, MuscleGroup.FullBody, 8.0),
        ("Dumbbell swing", Equipment.Dumbbell, MuscleGroup.FullBody, 8.0),
        ("Russian twist", Equipment.Dumbbell, MuscleGroup.Core, 3.5),
        ("Kettlebell swing", Equipment.Kettlebell, MuscleGroup.FullBody, 8.0),
        ("Kettlebell goblet squat", Equipment.Kettlebell, MuscleGroup.Legs, 5.0),
        ("Kettlebell clean and press", Equipment.Kettlebell, MuscleGroup.FullBody, 8.0),
        ("Turkish get-up", Equipment.Kettlebell, MuscleGroup.FullBody, 6.0),
        ("Push-up", Equipment.Bodyweight, MuscleGroup.Chest, 5.0),
        ("Diamond push-up", Equipment.Bodyweight, MuscleGroup.Arms, 5.0),
        ("Pike push-up", Equipment.Bodyweight, MuscleGroup.Shoulders, 5.0),
        ("Pull-up", Equipment.Bodyweight, MuscleGroup.Back, 6.0),
        ("Chin-up", Equipment.Bodyweight, MuscleGroup.Back, 6.0),
        ("Inverted row", Equipment.Bodyweight, MuscleGroup.Back, 5.0),
        ("Bodyweight squat", Equipment.Bodyweight, MuscleGroup.Legs, 5.0),
        ("Jump squat", Equipment.Bodyweight, MuscleGroup.Legs, 8.0),
        ("Reverse lunge", Equipment.Bodyweight, MuscleGroup.Legs, 5.0),
        ("Glute bridge", Equipment.Bodyweight, MuscleGroup.Legs, 3.5),
        ("Wall sit", Equipment.Bodyweight, MuscleGroup.Legs, 3.5),
        ("Bench dip", Equipment.Bodyweight, MuscleGroup.Arms, 5.0),
        ("Plank", Equipment.Bodyweight, MuscleGroup.Core, 3.5),
        ("Side plank", Equipment.Bodyweight, MuscleGroup.Core, 3.5),
        ("Dead bug", Equipment.Bodyweight, MuscleGroup.Core, 3.5),
        ("Bicycle crunch", Equipment.Bodyweight, MuscleGroup.Core, 3.5),
        ("Leg raise", Equipment.Bodyweight, MuscleGroup.Core, 3.5),
        ("Hollow hold", Equipment.Bodyweight, MuscleGroup.Core, 3.5),
        ("Mountain climber", Equipment.Bodyweight, MuscleGroup.FullBody, 8.0),
        ("Burpee", Equipment.Bodyweight, MuscleGroup.FullBody, 8.0),
        ("Bear crawl", Equipment.Bodyweight, MuscleGroup.FullBody, 6.0),
        ("Ab wheel rollout", Equipment.AbWheel, MuscleGroup.Core, 5.0),
        ("Kneeling ab wheel rollout", Equipment.AbWheel, MuscleGroup.Core, 3.5),
        ("Ab wheel plank hold", Equipment.AbWheel, MuscleGroup.Core, 3.5),
        ("Band pull-apart", Equipment.Band, MuscleGroup.Shoulders, 3.5),
        ("Band row", Equipment.Band, MuscleGroup.Back, 3.5),
        ("Band squat", Equipment.Band, MuscleGroup.Legs, 5.0),
        ("Band bicep curl", Equipment.Band, MuscleGroup.Arms, 3.5),
        ("Band glute kickback", Equipment.Band, MuscleGroup.Legs, 3.5),
    ];
}
